### ISSUE TITLE
Improve Repairnator support for different modes

### ISSUE THREAD

**Issue by bloriot97** [Spirals-Team/repairnator#761] opened 2018-10-23 07:48 UTC
Currently Repairnator support 2 different modes _repair_ and _bears_.
But I'm currently adding a new mode for repair of checkstyle errors. Which rise the total number of modes to 3.
What I have done so far is add a --checkstyle flag but in my opinions it makes the things bit messy. 

My proposal it to change the --bears and --checkstyle flags for a --mode option.

Also (in my case at least) I don't really see the point of having different docker images for every Repairnator's mode. I would rather suggest to run different scripts depending on the `REPAIR_MODE` environment variable.

**Comment by surli** [comment] 2018-10-23 08:01
> I'm currently adding a new mode for repair of checkstyle errors.

Not sure why it's a new mode: isn't it a new repair?

>  I don't really see the point of having different docker images for every Repairnator's mode. I would rather suggest to run different scripts depending on the REPAIR_MODE environment variable.

Agree with you generally. Now historically it was easier for me and @fermadeiral to manage our own stuff in our side :) We could/should refactor that at a point, but it also depends how much bears becomes a side-project that uses repairnator or not (political discussion around bears).

**Comment by bloriot97** [comment] 2018-10-23 08:29
> Not sure why it's a new mode: isn't it a new repair?

The percentage project having checkstyle rules is small and the percentage of failing build because of checkstyle is even smaller so with @monperrus we have decided to run it as a specific instance that will just focus on the build that appears to have checkstyle issues. 

> We could/should refactor that at a point

Fine, then for now should a keep going with my --checkstyle flag ?

**Comment by fermadeiral** [comment] 2018-10-23 08:33
@bloriot97 the bears mode will be deleted very soon from repairnator, thus I suggest you to try to think the best way to integrate your new mode without having bears as a parameter, i.e. you don't need to do the stuff in the same way that it was for bears.

**Comment by fermadeiral** [comment] 2018-10-23 08:34
> Fine, then for now should a keep going with my --checkstyle flag ?

For me, this is just fine.

**Comment by fermadeiral** [comment] 2018-10-23 15:43
I think that I agree with @bloriot97.

The checkstyle repair tool would be different from the current repair tools in two ways: 1) it does not target test failure like the current repair tools (i.e. even the maven invocation will be different), and 2) the change in the code is on "formatting", not on logical stuff.

For these reasons, I think reasonable to have a mode specific for it, but not having that it's possible to make it work too.

**Comment by bloriot97** [comment] 2018-10-24 12:20
The problem of implementing it as a repair tool is that I do not need to run through the exact same steps needed for normal program repair and the behavior of other feature than the pipeline may be different.
For example the rt_scanner will focus on failing build having checkstyle rules specified in the pom.xml. 

The aim is to focus on failing build only caused by checkstyle errors. For example see [this one](https://travis-ci.org/danglotb/dspot/builds/445509454).

**Comment by bloriot97** [comment] 2018-10-24 12:21
But it could also be interesting to implement it as a repair tool because then you could fix build having both checkstyle errors and failing tests.

**Comment by surli** [comment] 2018-10-24 12:46
On the short term, I agree that we can keep with the `--checkstyle` flag.
But on a long term view, I maintain my position here: I don't agree with your argument about the pipeline following different steps for fixing checkstyle issues. It's already the case when fixing NPE: we trigger this step only if a specific condition is encountered.

Now it might need some changes in Repairnator architecture for that :)

**Comment by fermadeiral** [comment] 2018-10-24 13:07
> It's already the case when fixing NPE: we trigger this step only if a specific condition is encountered.

The specific condition is a specific test error, encountered by running tests. In the case of the checkstyle, no tests need to be executed.

If the flag on checkstyle doesn't exist, a workaround could be something like: if in the list of repair tools that was give as argument only contains the one that repairs checkstyle issues, the test execution is skipped, and the checkstyle inspection is executed.

**Comment by fermadeiral** [comment] 2018-10-25 12:33
Hi boys. I have done some thought about this issue, and I think that the discussion here is far from being clear, so I suggest we try to do that for once.

I think that the discussion on "modes" goes beyond "modes", i.e. there are a lot of things that would be impacted on the code itself and architecture (e.g. `ProjectInspector`, docker images, scripts, creation of new pipeline steps, etc.), and I gave my opinion on the "mode" based on no clear context, which is pretty bad. So I would like to have a full and clear vision on what is going on. I list here some questions, and I would really appreciate the answers for them:

1) Repairnator does not implement repair tools: it reproduces failures and try to repair them with tools that are integrated on it. Is the checkstyle error repair tool going to be implemented inside Repairnator, or is it going to be an external tool that will be integrated on Repairnator (like Repairnator works right now)?

2) Is the checkstyle error repair tool going to be executed alone, always, forever? In my vision, one might want to execute Repairnator with all tools, i.e. both java repair tools (the existing ones) and the checkstyle tool. However, depending on how this is implemented, it will not be possible to run everything together.

**Comment by surli** [comment] 2018-10-25 12:41
> So I would like to have a full and clear vision on what is going on. 

I personally have a pretty clear vision on "how it should work", but not necessarily on "how that can be done" :)
So, for me Repairnator is a tool that repair failures. Any kind of failures, we don't care if it's a build failing because of a test, because of a checkstyle, because some coverage threshold is not reached, or whatever.
So as long as we add a mechanism that **repair** it's not a new mode.

Now I agree that **internally** it means the pipeline should be built in a different way, given the kind of failure the user wants to fix: and we know what the user wants to fix based on the tools she chosed.

So to answer your questions:

  1. We should always consider the repair tools as external from Repairnator. They are blackbox and *for now* I suggest that we never rely on the result of one repair tool to run another tool.

  2. We cannot make that assumption. All repair tools should be able to be launched together on repairnator. But as I said in 1. they don't collaborate: they work as independent blackboxes.

**Comment by fermadeiral** [comment] 2018-10-25 12:55
@surli thanks for answering me.

> I personally have a pretty clear vision on "how it should work", but not necessarily on "how that can be done" :)

Good, me too. What I don't have a clear view in on what is going on, like I said before. I have had mixed signals in this discussion.

> So, for me Repairnator is a tool that repair failures. Any kind of failures, we don't care if it's a build failing because of a test, because of a checkstyle, because some coverage threshold is not reached, or whatever.

I'm with your thought on this.

> So as long as we add a mechanism that repair it's not a new mode.

Yes, this is what I still don't know on what to think, because as I said, I have had mixed signals.

> We should always consider the repair tools as external from Repairnator.

I completely agree, but my question was not on what we "should", and how this is going to happen, because what we should might be very different on what is going on (which I don't know :).

> We cannot make that assumption. All repair tools should be able to be launched together on repairnator.

I agree again. But since @bloriot97 said this: "so with @monperrus we have decided to run it as a specific instance that will just focus on the build that appears to have checkstyle issues.", everything was messed up in my mind.

See that I'm not against anything here, and I have a pretty good view on the goal of Repairnator. I'm just not sure that all of us are aligned, and this is why I wanted to discuss that properly, before the things get messy and rework be required.

**Comment by surli** [comment] 2018-10-25 13:28
> I agree again. But since @bloriot97 said this: "so with @monperrus we have decided to run it as a specific instance that will just focus on the build that appears to have checkstyle issues.", everything was messed up in my mind.

If I understand well you want the agreement from @monperrus, @bloriot97 and @btellstrom that we all share the same vision.

Now I might be wrong on this, but for me here @monperrus just meant "let's do a trial really scoped and we'll see later if it can be improved/mixed with other tools".
We basically did the same with AssertFixer, a tool developed by @danglotb. 

Now just to ponderate everything I said: I know the experiment might be urgent, that's why I understood we do not follow always the vision above to be able to get results quickly. That's why I agreed earlier on using a new mode for checkstyle, as it's easier for now to implement.

**Comment by fermadeiral** [comment] 2018-10-25 13:44
> If I understand well you want the agreement from @monperrus, @bloriot97 and @btellstrom that we all share the same vision.

Yes. If the vision is not the same, it's not really possible to discuss things properly, not even review properly PRs, and worse, there is no good way to ensure that nothing is being broken.

> Now I might be wrong on this, but for me here @monperrus just meant "let's do a trial really scoped and we'll see later if it can be improved/mixed with other tools".

Thank you for clarifying that to me.

> Now just to ponderate everything I said: I know the experiment might be urgent, that's why I understood we do not follow always the vision above to be able to get results quickly. That's why I agreed earlier on using a new mode for checkstyle, as it's easier for now to implement.

Ok, now I understand your point in particular, and I think the same: it's important to find a balance between doing the things in the "properly" way and the way to implement the things faster and easily to get results.

Thanks a lot for the answer, this is clarifier.

**Comment by monperrus** [comment] 2018-10-25 15:03
Thanks a lot Fernanda for helping aligning our vision.

> We should always consider the repair tools as external from Repairnator. 

Correct. And repair-checkstyle is no exception, it will live on another repo, and will be called from Repairnator.

> it's important to find a balance between doing the things in the "properly" way and the way to implement the things faster and easily to get results.

Fully agree. This is the art of doing collaborative software development for research in unknown territories.

**Comment by monperrus** [comment] 2019-03-18 16:47
closed by #797

**Closed by monperrus** 2019-03-18 16:47 UTC
