### ISSUE TITLE
About the timezone

### ISSUE THREAD

**Issue by bloriot97** [Spirals-Team/repairnator#772] opened 2018-10-26 12:58 UTC
I am facing some issues with the timezone and the REST api.

The time zone in the docker image for the pipeline is set to "Europe/Paris" but when repairnator insert a value in the database it ends up being a referenced as UTC time while it is actually at Paris time.
The result is that if I select something for example in the past 24 hours in the api I will have a 2 hours delay. Of course I could add 2 hours but it would be prompt for errors I think.

My proposal is to integrate the timezone in the serializers. 

P.S. The lucky part is that next week I will only have a one hour delay... :tada:

**Comment by surli** [comment] 2018-10-26 13:05
I agree there's certainly a problem with the TZ. Not sure though about what you mean by: 
> My proposal is to integrate the timezone in the serializers.

IMO the data should be always stored with UTC time. So indeed if the data is computed on a computer with UTC+2, the dates should be fixed before recording.

I'm not sure we can only put the TZ in the date before pushing it in the DB, because if I'm write we record the dates both in Date() object and in string. We should keep consistency between them.

**Comment by fermadeiral** [comment] 2018-10-26 13:12
I'm not sure in which dates there is an issue, but depending in which dates are, we should be careful also thinking about jtravis, no? Because we rely on jtravis for several things, and jtravis uses time for several things. My point is that we need take care to not change stuff that should not be changed.

So I would like to know which types of date we have an issue with. For instance, which attribute was used in the database for this query: "The result is that if I select something for example in the past 24 hours"?

**Comment by fermadeiral** [comment] 2018-10-26 13:14
A question: if we change the way to store the dates in question, should we update the entire database accordingly?

**Comment by bloriot97** [comment] 2018-10-26 13:17
In mongodb I think we can reference the date as `ISODate("2018-10-26T16:00:00.000+02:00")` for instance. 
But it may also be prompt to errors then maybe we should store with UTC time

> So indeed if the data is computed on a computer with UTC+2, the dates should be fixed before recording.

Then for example for the pipeline a solution could be to change this [line](https://github.com/Spirals-Team/repairnator/blob/master/repairnator/docker-images/pipeline-dockerimage-dev/Dockerfile#L16)? But then we could face some inconsistency with rest of repairnator that is outside the container if the timezone is not the same.

**Comment by bloriot97** [comment] 2018-10-26 13:29
> I'm not sure in which dates there is an issue

@fermadeiral for instance this is a recent record that has been added to the inspector collection.
```js
{
	...
	"status" : "NOTBUILDABLE",
	"prNumber" : 0,
	"buildFinishedDateStr" : "26/10/18 15:03",
	"buildFinishedDate" : ISODate("2018-10-26T15:03:28Z"),
	"buildFinishedDay" : "26/10/2018",
	"realStatus" : "[ CloneRepository : SUCCESS ] -> [ CheckoutBuggyBuild : SUCCESS ] -> [ BuildProject : FAILURE ( NOTBUILDABLE ) ]",
	"hostname" : "repairnator-desktop",
	"buildReproductionDateStr" : "26/10/18 15:06",
	"buildReproductionDate" : ISODate("2018-10-26T15:06:01.226Z"),
        ...
}
```
The pipeline finished its work at "15:06 GMT+2" so "13:06 UTC"  but it is recorded as "15:06 UTC".

Then if the API query the results of the past 24 hours it will query the data from "yesterday 13:06 UTC" to "today 13:06 UTC" then the result won't be included before 2 hours in the query.

**Comment by fermadeiral** [comment] 2018-10-26 13:37
@bloriot97 ok so you are using the date "buildReproductionDate". I see the problem you are facing =/

My concern is to change that and make it inconsistent with the dates related to the build, like "buildFinishedDate". Because, in the example you gave, for instance, if we change the "buildReproductionDate" to "13:06 UTC", it will be odd since it will indicate that the reproduction was before the build being finished.

**Comment by surli** [comment] 2018-10-26 13:45
As @fermadeiral said there is several things to take into account:
  - dates of the build on Travis,
  - dates produced by Repairnator and serialized
  - dates in the logs

I don't think we have to worry about JTravis itself: I've been careful to use UTC time everywhere.

Now as I said all serialized dates should use UTC instead of the UTC+2 we were using before. But we cannot do that by changing the Docker TZ: we cannot rely on that, an user might run Repairnator on its own machine without docker, or we could build another docker image with another TZ or whatever.

However, we should enforce the date serialization to use UTC date. I think it could be done by changing those methods: https://github.com/Spirals-Team/repairnator/blob/master/repairnator/repairnator-core/src/main/java/fr/inria/spirals/repairnator/Utils.java#L40-L50

**Comment by fermadeiral** [comment] 2018-10-26 13:54
> I don't think we have to worry about JTravis itself: I've been careful to use UTC time everywhere.

I didn't mean that something is wrong on jtravis side at all. In fact it was the opposite: I'm worried that changes be done in the dates from jtravis, which I don't think that should happen (this was my concern). I brought jtravis in the discussion because in that point of the discussion I didn't know exactly which dates @bloriot97 was referring to. But now I got that the issue is on the reproduction date.

**Comment by fermadeiral** [comment] 2018-10-29 13:15
Should the "buildReproductionDate" be the beginning of the reproduction or the end?

**Comment by bloriot97** [comment] 2018-11-01 13:44
@surli there is something I don't understand with the dates on jTravis.

For example [this](https://travis-ci.org/Spirals-Team/repairnator/builds/449321554?utm_source=github_status&utm_medium=notification) build ended at 14:15:19 GMT+1, few minutes before this post. But in the database we have `buildFinishedDate : Thu Nov 01 2018 14:15:19 GMT+0000 (UTC)` which is inconsistent, it should be 13:15:19 UTC.
 
Maybe there is an issue with the serializer or a matter of conversion ?

**Comment by monperrus** [comment] 2018-11-05 13:38
It seems we all agree that all data in the database should be UTC-based.

But @bloriot97 tells us that it's unclear where the bug is, @surli what do you think of https://github.com/Spirals-Team/repairnator/issues/772#issuecomment-435045245?

**Comment by surli** [comment] 2018-11-05 14:15
weird I though I had answered this one... 

> Maybe there is an issue with the serializer or a matter of conversion ?

So it's pretty sure there is a bug yes :) Not sure where it is exactly.
You should debug it and checked if the date given by jTravis has the right timezone.
If it's the case, then the bug should be somewhere when serializing the date.
I checked the code quickly but did not find anything weird with a quicklook.

**Closed** 2019-03-27 16:58 UTC
